version: '3.8'

services:
    # Service สำหรับ PHP Application
    app:
        build:
            context: ./docker/php
            dockerfile: Dockerfile
            args:
                user: sail
                uid: 1000
        container_name: tms_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - db
            - redis
        networks:
            - tms_network

    # Service สำหรับ Web Server (Nginx)
    nginx:
        image: nginx:alpine
        container_name: tms_nginx
        restart: unless-stopped
        ports:
            - "${APP_PORT:-8080}:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf # <-- แก้ไข: Mount ไฟล์ ไม่ใช่โฟลเดอร์
        depends_on:
            - app
        networks:
            - tms_network

    # *** ส่วนที่แก้ไข: เปลี่ยนเป็น PostgreSQL ***
    db:
        image: postgres:15-alpine
        container_name: tms_db
        restart: unless-stopped
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432" # <-- Port ของ Postgres
        environment:
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - tms_pg_data:/var/lib/postgresql/data # <-- Volume ของ Postgres
        networks:
            - tms_network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
            interval: 10s
            timeout: 5s
            retries: 5
    # *** สิ้นสุดส่วนที่แก้ไข ***

    # Service สำหรับ Cache & Queue (Redis)
    redis:
        image: redis:alpine
        container_name: tms_redis
        restart: unless-stopped
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - tms_redis_data:/data
        networks:
            - tms_network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
            
    # Service สำหรับ Email Catcher (Mailpit)
    mailpit:
        image: 'axllent/mailpit:latest'
        container_name: tms_mailpit
        restart: unless-stopped
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - tms_network

networks:
    tms_network:
        driver: bridge

volumes:
    tms_pg_data: # <-- เปลี่ยนชื่อ Volume
        driver: local
    tms_redis_data:
        driver: local